language: python
cache:
  pip: true
  directories:
  - node_modules


matrix:
  include:
    - os: linux
      dist: xenial  # Ubuntu 16.04
      python: 3.6
      env: TOXENV=py36
    - os: linux
      dist: bionic  # Ubuntu 18.04
      python: 3.6
      env: TOXENV=py36
    - os: linux
      dist: bionic  # Ubuntu 18.04
      python: 3.7
      env: TOXENV=py37
    # - os: osx
    #   osx_image: xcode9.4
    #   language: generic
    #   env: TOXENV=py36
    #   addons:
    #     homebrew:
    #       # update: true
    #       packages: python3.6
    #   before_install:
    #     - pip3 install virtualenv
    #     - virtualenv -p python3 ~/venv
    #     - source ~/venv/bin/activate

install:
  - sudo pip install tox

script:
  - tox --sitepackages
  - pip install --editable .

after_success:
  - pip install -r ./docs/requirements.txt
  - python3 setup.py sdist bdist_wheel
  - bash gen_docs.sh
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GH_TOKEN
  local-dir: docs/build/html
  on:
    branch: master
  provider: pypi
  user: $PYPI_NAME
  password: $PYPI_KEY
  on:
    tags: true