language: python
cache:
  pip: true
  directories:
  - node_modules
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - touch XD
  - rm XD
deploy:
  provider: pypi
  user: $PYPI_NAME
  password: $PYPI_KEY
  on:
    tags: true